
title: Akxr's LiveJournal
email: aksharu73@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sup! I Post my blogs here, just to carry the vibe, The parallel blogging when Zuck was Hacking into the Harvard..That Scene was soo cold!.. Happy to see you here!
baseurl: "https://github.com/Akshar-u-2077" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
