
title: "Akxr's LiveJournal"
email: aksharu73@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sup! I post my blogs here, just to carry the vibe — the parallel blogging
  when Zuck was hacking into Harvard... That scene was sooo cold! 
  Happy to see you here!

url: "https://akxr007.github.io"
baseurl: "" # leave empty for user site (akxr007.github.io)

# Social handles
twitter_username: jekyllrb
github_username: Akshar-u-2077

# Theme
theme: minima

# Build settings
markdown: kramdown


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
